name: dotnet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'


defaults:
  run:
    working-directory: ./
    
jobs:
  build:
    runs-on: windows-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish src/Shotr.Ui -r win-x64 -c BetaTest
    - uses: actions/upload-artifact@v2
      with:
        name: Shotr
        path: ./src/Shotr.Ui/bin/BetaTest/net5.0-windows10.0.19041.0/win-x64/publish/Shotr.exe
    - uses: actions/comment@2
  comment-on-pr:
    name: Leave a comment with a link to the build on the PR
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment( {
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'The artifact is located here: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}#artifacts' 
          } )
